version: "2"
services:
  web:
    build: ./web
    ports:
      - "3000:3000"
    volumes:
      - ./web/app:/app
  notify:
    ports:
      - "3001:3000"
    build: ./notify-service
    volumes:
      - ./notify-service/app:/app
  db:
    ports:
      - "3306:3306"
    build:
      context: ./database
    environment:
      - MYSQL_ROOT_PASSWORD=changeme
